name: Train Model CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: wine-env
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . --no-conda
