name: Train Wine Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install -r MLProject/requirements.txt

    - name: Run Training Script
      run: |
        python MLProject/modelling.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wine-model-artifacts
        path: |
          MLProject/classification_report.csv
          MLProject/model.pkl
